version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
    - checkout
    - restore_cache:
        keys:
            - sfdx-version-41-local
    - run:
        name: Install Salesforce DX
        command: |
            openssl enc -nosalt -aes-256-cbc -d -in assets/server.key.enc -out assets/server.key -base64 -K 954C6D0DA031828E12471D02D71E873C448D00EEBC93FD9185C4611D2C3284D5 -iv 9CBA503D217EF09B4CD6FE8F237664AD
            
            npm install sfdx-cli
            node_modules/sfdx-cli/bin/run --version
            node_modules/sfdx-cli/bin/run plugins --core
    - run:
          name: Create Scratch Org
          command: |
              node_modules/sfdx-cli/bin/run sfdx force:auth:sfdxurl:store -f assets/sfdxurl.txt -a circleci-org
              node_modules/sfdx-cli/bin/run force:org:create -v DevHub -s -f config/project-scratch-def.json -a scratch
    - run:
          name: Remove Server Key
          when: always
          command: |
              rm assets/server.key
              
